name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Replace __WS_URL__ with Vercel WebSocket URL
        run: |
          WS_URL="wss://puzzle-game-superchat-backend.vercel.app"
          sed -i "s|__WS_URL__|$WS_URL|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
